### ISSUE TITLE
Okay so... How do you use it?

### ISSUE THREAD

**Issue by time-less-ness** [jpmcb/nvim-llama#2]
I've installed it. I've required it. I've set it up... What do I do now? Is there some command in the editor window I should use?

You should give example usage in your README.md. I've looked at the source code and found nothing obvious.

**Comment by gjedeer** [comment]
I had the same questions and found that there's almost no code in this repo. It's an early work in progress.

**Comment by jpmcb** [comment]
Thanks for the issue: yes, it's an early work in progress and proof of concept. Here's how you can set it up:

1. Build and install llama.cpp with the `:LlamaInstall` autocommand - this will grab llama.cpp, build it, and make the llama runner available to your nvim context. ⚠️ _Warning!!!_ You need the c/c++ build toolchain to make this happen. Primarily, you need cmake.
2. You need to download a model as a gguf file. There are alot you can use from Hugging Face, but here's a script you can use to get the CodeLlama 13 billion parameter model:

```sh
#!/bin/bash

# This is an example convenience script to demonstrate downloading the 13b GGUF
# model for llama.cpp from Huggingface.
#
# It drops the model into the expected directory for nvim-llama and llama.cpp to
# be able to utilize it

LLAMA_CPP_CLONE="~/.local/share/nvim/llama.cpp"
MODEL="codellama-13b.Q4_K_M.gguf"

pushd "${LLAMA_CPP_CLONE}"
    if [ ! -f models/${MODEL} ]; then
        curl -L "https://huggingface.co/TheBloke/CodeLlama-13B-GGUF/resolve/main/${MODEL}" -o models/${MODEL}
    fi
popd
```

Run this from where your system installed llama.cpp which should be `~/.local/share/nvim/llama.cpp`: this will drop the model into the `models` directory in llama.cpp which is where it looks for models to run.

⚠️ - _warning!!!_ You need to accept Meta's open source agreement and license to use this specific model - https://ai.meta.com/llama/ distributing LLM ggufs is out of scope of this project. But in the future I hope to integrate ollama to integrate easier downloading of models

3. Now, you should be able to run the `:Llama` autocommand to open a prompt with your downloaded model.

---

Again, this is a rough proof of concept plugin and is more or less intended to show the possibility of running big large language models locally on consumer based hardware for nvim purposes.

I'm planning to abstract almost all those steps away by using ollama in the future (since it doesn't require a c/c++ buildchain, just docker).

Look forward to that soon and thanks for checking out the project!!!

**Comment by jpmcb** [comment]
Closing as I've just shipped the ollama integration: now, all you need is:

- docker installed on your system
- install the plugin via your favorite package manager
- set it up in your lua configs: `require('nvim-llama').setup {}`
- start using it with the `:Llama` autocommand
